
name: GitHub Pages
run-name: ${{ github.actor }} is running an action

on:
  push:
    branches:
    - main

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build
      run: npm run build
      
    - name: Deploy
      if: success()
      run: ./node_modules/.bin/ng deploy --base-href=/tp-gh-pages/ --repo=https://github.com/arendsyl/tp-gh-pages.git
