
name: GitHub Pages
run-name: ${{ github.actor }} is running an action

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build
      run: npm run build
      
    - name: Archive artifact
      shell: bash
      if: runner.os == 'Linux'
      run: |
        tar \
          --dereference --hard-dereference \
          --directory "$INPUT_PATH" \
          -cvf "$RUNNER_TEMP/artifact.tar" \
          --exclude=.git \
          --exclude=.github \
          .
      env:
        INPUT_PATH: dist/demo-gh-pages
        
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.1
      with:
        artifact_name: demo-gh-pages
