name: Lint code on PR submit
run-name: ${{ github.actor }} is running an action
on:
  pull_request:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
    
    - name: Format Check
      run: npm run check
    